export enum CaptchaFor {
  CAPTCHA_FOR_RESET_PASSWORD = 'CAPTCHA_FOR_RESET_PASSWORD',
  CAPTCHA_FOR_VERIFY_EMAIL = 'CAPTCHA_FOR_VERIFY_EMAIL',
  CAPTCHA_FOR_CHANGE_USERNAME = 'CAPTCHA_FOR_CHANGE_USERNAME',
  CAPTCHA_FOR_CHANGE_EMAIL = 'CAPTCHA_FOR_CHANGE_EMAIL',
  CAPTCHA_FOR_DELETE_ACCOUNT = 'CAPTCHA_FOR_DELETE_ACCOUNT',
}
